use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum RustType {
    Bool,
    I64,
    F64,
    String,
    Value,
    Array(Box<RustType>),
    Struct(String),
    Enum(String),
}

#[derive(Debug, Clone, Eq, PartialEq)]
struct Version {
    major: u32,
    minor: u32,
    patch: u32,
    original: String,
}

impl Ord for Version {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.major.cmp(&other.major)
            .then(self.minor.cmp(&other.minor))
            .then(self.patch.cmp(&other.patch))
    }
}

impl PartialOrd for Version {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

fn parse_version(s: &str) -> Version {
    let clean = s.trim_start_matches('v');
    let parts: Vec<&str> = clean.split('.').collect();
    let major = parts.get(0).and_then(|p| p.parse().ok()).unwrap_or(0);
    let minor = parts.get(1).and_then(|p| p.parse().ok()).unwrap_or(0);
    let patch = parts.get(2).and_then(|p| p.parse().ok()).unwrap_or(0);
    Version {
        major,
        minor,
        patch,
        original: s.to_string(),
    }
}

struct GeneratedComponent {
    version_mod: String,
    type_names: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=schemas/minecraftBedrock/schema/item");

    generate_schemas("item".to_string());
    generate_schemas("block".to_string());
}

fn generate_schemas(ty: String) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_path = Path::new(&manifest_dir).join(format!("schemas/minecraftBedrock/schema/{}", ty));
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join(format!("{}/components.rs", ty));

    _ = fs::create_dir_all(&dest_path.parent().unwrap());

    let version_dirs = find_version_dirs(&base_path);
    let mut generated_code = String::new();

    generated_code.push_str("// This file is auto-generated by build.rs. Do not edit manually.\n\n");

    let mut active_components: std::collections::HashMap<String, GeneratedComponent> = std::collections::HashMap::new();

    for (version, components_path) in version_dirs {
        let mod_name = version.original.replace('.', "_");
        generated_code.push_str(&format!("pub mod {} {{\n", mod_name));

        let mut definitions = Vec::new();
        let mut local_components = std::collections::HashSet::new();

        if let Ok(entries) = fs::read_dir(&components_path) {
            let mut file_paths: Vec<PathBuf> = entries
                .filter_map(|e| e.ok().map(|entry| entry.path()))
                .filter(|path| {
                    path.is_file()
                        && path.extension().map_or(false, |ext| ext == "json")
                        && !path.file_name().unwrap().to_string_lossy().starts_with('_')
                })
                .collect();

            file_paths.sort();

            for file_path in file_paths {
                let file_stem = file_path.file_stem().unwrap().to_string_lossy().to_string();
                let root_name = to_pascal_case(&file_stem);

                let content = match fs::read_to_string(&file_path) {
                    Ok(c) => c,
                    Err(_) => continue,
                };
                let clean_content = strip_comments(&content);
                let schema_val: Value = match serde_json::from_str(&clean_content) {
                    Ok(v) => v,
                    Err(e) => {
                        println!("cargo:warning=Failed to parse JSON schema {:?}: {}", file_path, e);
                        continue;
                    }
                };

                let mut file_type_names = Vec::new();
                let root_type = parse_schema(&file_path, &schema_val, &root_name, &mut definitions, &mut file_type_names);

                if !matches!(root_type, RustType::Struct(_) | RustType::Enum(_)) {
                    let root_type_str = to_rust_type_string(&root_type);
                    let newtype_def = format!(
                        "#[derive(serde::Serialize, Clone, Debug, PartialEq)]\npub struct {}(pub {});\n\n",
                        root_name, root_type_str
                    );
                    definitions.push(newtype_def);
                    file_type_names.push(root_name.clone());
                }

                let component_id = format!("minecraft:{}", file_stem);
                let impl_component = format!(
                    "impl super::Component for {} {{\n    const ID: &'static str = \"{}\";\n}}\n",
                    root_name, component_id
                );
                definitions.push(impl_component);

                let impl_direct_id = format!(
                    "impl {} {{\n    pub const ID: &'static str = \"{}\";\n}}\n",
                    root_name, component_id
                );
                let impl_sjson = format!(
                    "impl eo::sjson::HasSJsonIdent for {} {{ fn sjson_ident(&self) -> String {{ \"{}\".to_string() }} }}",
                    root_name, component_id
                );
                definitions.push(impl_direct_id);

                definitions.push(impl_sjson);

                local_components.insert(file_stem.clone());
                active_components.insert(file_stem.clone(), GeneratedComponent {
                    version_mod: mod_name.clone(),
                    type_names: file_type_names,
                });
            }
        }


        for def in &definitions {
            for line in def.lines() {
                generated_code.push_str(&format!("    {}\n", line));
            }
            generated_code.push_str("\n");
        }

        let mut inherited_re_exports = Vec::new();
        for (comp_name, gen_comp) in &active_components {
            if !local_components.contains(comp_name) {
                for t_name in &gen_comp.type_names {
                    inherited_re_exports.push(format!("    pub use super::{}::{};\n", gen_comp.version_mod, t_name));
                }
            }
        }
        inherited_re_exports.sort();

        if !inherited_re_exports.is_empty() {
            generated_code.push_str("    // Inherited components re-exports\n");
            for re_export in inherited_re_exports {
                generated_code.push_str(&re_export);
            }
            generated_code.push_str("\n");
        }

        generated_code.push_str("}\n\n");
    }

    fs::write(&dest_path, generated_code).unwrap();
}

fn find_version_dirs(base_path: &Path) -> Vec<(Version, PathBuf)> {
    let mut versions = Vec::new();
    if let Ok(entries) = fs::read_dir(base_path) {
        for entry in entries {
            if let Ok(entry) = entry {
                let path = entry.path();
                if path.is_dir() {
                    let name = path.file_name().unwrap().to_string_lossy().to_string();
                    if name.starts_with('v') {
                        let components_path = path.join("components");
                        if components_path.is_dir() {
                            versions.push((parse_version(&name), components_path));
                        }
                    }
                }
            }
        }
    }
    versions.sort_by(|a, b| a.0.cmp(&b.0));
    versions
}

fn strip_comments(json_str: &str) -> String {
    let mut result = String::new();
    let mut in_string = false;
    let mut is_escaped = false;
    let mut chars = json_str.chars().peekable();
    while let Some(c) = chars.next() {
        if in_string {
            result.push(c);
            if c == '\\' {
                is_escaped = !is_escaped;
            } else if c == '"' && !is_escaped {
                in_string = false;
            } else {
                is_escaped = false;
            }
        } else {
            if c == '"' {
                in_string = true;
                result.push(c);
            } else if c == '/' && chars.peek() == Some(&'/') {
                chars.next();
                while let Some(&nc) = chars.peek() {
                    if nc == '\n' || nc == '\r' {
                        break;
                    }
                    chars.next();
                }
            } else if c == '/' && chars.peek() == Some(&'*') {
                chars.next();
                while let Some(nc) = chars.next() {
                    if nc == '*' && chars.peek() == Some(&'/') {
                        chars.next();
                        break;
                    }
                }
            } else {
                result.push(c);
            }
        }
    }
    result
}

fn normalize_path(path: &Path) -> PathBuf {
    use std::path::Component;
    let mut comps = Vec::new();
    for comp in path.components() {
        match comp {
            Component::ParentDir => {
                comps.pop();
            }
            Component::CurDir => {}
            Component::Normal(c) => {
                comps.push(c);
            }
            Component::RootDir => {
                comps.clear();
                comps.push(std::ffi::OsStr::new("/"));
            }
            _ => {}
        }
    }
    let mut result = PathBuf::new();
    for c in comps {
        result.push(c);
    }
    result
}

fn resolve_ref(current_file: &Path, ref_str: &str) -> (PathBuf, Value) {
    let parts: Vec<&str> = ref_str.split('#').collect();
    let file_path = if parts[0].is_empty() {
        current_file.to_path_buf()
    } else {
        current_file.parent().unwrap().join(parts[0])
    };
    let file_path = normalize_path(&file_path);

    let content = fs::read_to_string(&file_path)
        .unwrap_or_else(|e| panic!("Failed to read referenced file {:?}: {}", file_path, e));
    let clean_content = strip_comments(&content);
    let mut val: Value = serde_json::from_str(&clean_content)
        .unwrap_or_else(|e| panic!("Failed to parse JSON from {:?}: {}", file_path, e));

    if parts.len() > 1 && !parts[1].is_empty() {
        let pointer = parts[1];
        let normalized_pointer = if pointer.starts_with('/') {
            pointer.to_string()
        } else {
            format!("/{}", pointer)
        };
        if let Some(sub_val) = val.pointer(&normalized_pointer) {
            val = sub_val.clone();
        } else {
            panic!("Could not find pointer {} in {:?}", pointer, file_path);
        }
    }

    (file_path, val)
}

fn dereference(
    current_file: &Path,
    schema: &Value,
    depth: usize,
) -> (PathBuf, Value) {
    if depth > 30 {
        return (current_file.to_path_buf(), Value::Null);
    }
    if let Some(ref_str) = schema.get("$ref").and_then(|v| v.as_str()) {
        let (file_path, referenced_schema) = resolve_ref(current_file, ref_str);
        dereference(&file_path, &referenced_schema, depth + 1)
    } else {
        (current_file.to_path_buf(), schema.clone())
    }
}

fn parse_schema(
    current_file: &Path,
    schema: &Value,
    name_path: &str,
    definitions: &mut Vec<String>,
    type_names: &mut Vec<String>,
) -> RustType {
    let (resolved_file, deref_schema) = dereference(current_file, schema, 0);

    if let Some(any_of) = deref_schema.get("anyOf").or(deref_schema.get("oneOf")).and_then(|v| v.as_array()) {
        return parse_any_of(&resolved_file, any_of, name_path, definitions, type_names);
    }

    if let Some(all_of) = deref_schema.get("allOf").and_then(|v| v.as_array()) {
        let merged_schema = merge_all_of(&resolved_file, all_of);
        return parse_schema(&resolved_file, &merged_schema, name_path, definitions, type_names);
    }

    if let Some(type_val) = deref_schema.get("type") {
        match type_val {
            Value::String(t) => {
                match t.as_str() {
                    "boolean" => RustType::Bool,
                    "integer" => RustType::I64,
                    "number" => RustType::F64,
                    "string" => RustType::String,
                    "array" => {
                        let item_schema = deref_schema.get("items").unwrap_or(&Value::Null);
                        let inner_type = parse_schema(&resolved_file, item_schema, &format!("{}Item", name_path), definitions, type_names);
                        RustType::Array(Box::new(inner_type))
                    }
                    "object" => {
                        parse_object_schema(&resolved_file, &deref_schema, name_path, definitions, type_names)
                    }
                    _ => RustType::Value,
                }
            }
            Value::Array(arr) => {
                let any_of_schemas: Vec<Value> = arr.iter().map(|t| {
                    serde_json::json!({ "type": t })
                }).collect();
                parse_any_of(&resolved_file, &any_of_schemas, name_path, definitions, type_names)
            }
            _ => RustType::Value,
        }
    } else {
        if deref_schema.get("properties").is_some() {
            parse_object_schema(&resolved_file, &deref_schema, name_path, definitions, type_names)
        } else {
            RustType::Value
        }
    }
}

fn merge_all_of(current_file: &Path, schemas: &[Value]) -> Value {
    let mut merged_properties = serde_json::Map::new();
    for s in schemas {
        let (_, deref_s) = dereference(current_file, s, 0);
        if let Some(props) = deref_s.get("properties").and_then(|v| v.as_object()) {
            for (k, v) in props {
                merged_properties.insert(k.clone(), v.clone());
            }
        }
    }
    serde_json::json!({
        "type": "object",
        "properties": merged_properties
    })
}

fn parse_any_of(
    current_file: &Path,
    schemas: &[Value],
    name_path: &str,
    definitions: &mut Vec<String>,
    type_names: &mut Vec<String>,
) -> RustType {
    let mut deref_schemas = Vec::new();
    let mut object_count = 0;
    for s in schemas {
        let (resolved_file, deref_s) = dereference(current_file, s, 0);
        let is_obj = deref_s.get("properties").is_some()
            || deref_s.get("type").and_then(|t| t.as_str()).map_or(false, |t| t == "object");
        if is_obj {
            object_count += 1;
        }
        deref_schemas.push((resolved_file, deref_s));
    }

    let mut types = Vec::new();
    let mut obj_index = 0;
    for (i, (resolved_file, deref_s)) in deref_schemas.iter().enumerate() {
        let is_obj = deref_s.get("properties").is_some()
            || deref_s.get("type").and_then(|t| t.as_str()).map_or(false, |t| t == "object");

        let child_name = if is_obj {
            if object_count == 1 {
                format!("{}Object", name_path)
            } else {
                format!("{}Object{}", name_path, obj_index)
            }
        } else {
            format!("{}Option{}", name_path, i)
        };

        if is_obj {
            obj_index += 1;
        }

        let t = parse_schema(resolved_file, deref_s, &child_name, definitions, type_names);
        types.push(t);
    }

    let mut unique_types = Vec::new();
    let mut seen_type_strs = std::collections::HashSet::new();
    for t in types {
        let t_str = to_rust_type_string(&t);
        if !seen_type_strs.contains(&t_str) {
            seen_type_strs.insert(t_str.clone());
            unique_types.push(t);
        }
    }

    if unique_types.is_empty() {
        return RustType::Value;
    }
    if unique_types.len() == 1 {
        return unique_types[0].clone();
    }

    let enum_name = name_path.to_string();

    let mut enum_def = String::new();
    enum_def.push_str("#[derive(serde::Serialize, Clone, Debug, PartialEq)]\n");
    enum_def.push_str("#[serde(untagged)]\n");
    enum_def.push_str(&format!("pub enum {} {{\n", enum_name));

    for t in &unique_types {
        let variant_name = get_variant_name(t);
        let rust_type_str = to_rust_type_string(t);
        enum_def.push_str(&format!("    {}({}),\n", variant_name, rust_type_str));
    }

    enum_def.push_str("}\n");
    definitions.push(enum_def);
    type_names.push(enum_name.clone());

    RustType::Enum(enum_name)
}

fn parse_object_schema(
    current_file: &Path,
    schema: &Value,
    name_path: &str,
    definitions: &mut Vec<String>,
    type_names: &mut Vec<String>,
) -> RustType {
    let struct_name = name_path.to_string();

    let mut fields = Vec::new();
    if let Some(properties) = schema.get("properties").and_then(|v| v.as_object()) {
        let mut sorted_props: Vec<(&String, &Value)> = properties.iter().collect();
        sorted_props.sort_by_key(|(k, _)| *k);

        for (field_name, field_schema) in sorted_props {
            let (rust_field_name, rename_attr) = get_rust_field_name(field_name);
            let child_name_path = format!("{}{}", struct_name, to_pascal_case(field_name));
            let field_type = parse_schema(current_file, field_schema, &child_name_path, definitions, type_names);
            let field_type_str = to_rust_type_string(&field_type);
            fields.push((rust_field_name, field_type_str, rename_attr));
        }
    }

    let mut struct_def = String::new();
    struct_def.push_str("#[derive(derive_builder::Builder, serde::Serialize, Clone, Debug, PartialEq)]\n");
    struct_def.push_str("#[builder(setter(into))]\n");
    struct_def.push_str(&format!("pub struct {} {{\n", struct_name));
    for (f_name, f_type, rename_attr) in fields.clone() {
        if !rename_attr.is_empty() {
            struct_def.push_str(&format!("    {}\n", rename_attr));
        }
        struct_def.push_str("    #[builder(default = \"None\")]\n");
        struct_def.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        struct_def.push_str(&format!("    pub {}: Option<{}>,\n", f_name, f_type));
    }
    struct_def.push_str("}\n\n");
    struct_def.push_str(&format!("const _: () = {{\n    crate::hold_builders!({});\n}};\n", struct_name));

    definitions.push(struct_def);
    type_names.push(struct_name.clone());

    RustType::Struct(struct_name)
}

fn get_rust_field_name(name: &str) -> (String, String) {
    let keywords = [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "try",
    ];

    let cleaned = name.replace('*', "all").replace(':', "_").replace('$', "_");

    if keywords.contains(&cleaned.as_str()) {
        let rename_attr = format!("#[serde(rename = \"{}\")]", name);
        (format!("r#{}", cleaned), rename_attr)
    } else if cleaned != name {
        let rename_attr = format!("#[serde(rename = \"{}\")]", name);
        (cleaned, rename_attr)
    } else {
        (cleaned, String::new())
    }
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut next_upper = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' || c == ':' || c == '/' || c == '*' {
            next_upper = true;
        } else if next_upper {
            result.push(c.to_ascii_uppercase());
            next_upper = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn get_variant_name(t: &RustType) -> String {
    match t {
        RustType::Bool => "Bool".to_string(),
        RustType::I64 => "Integer".to_string(),
        RustType::F64 => "Number".to_string(),
        RustType::String => "String".to_string(),
        RustType::Value => "Value".to_string(),
        RustType::Array(inner) => format!("Array{}", get_variant_name(inner)),
        RustType::Struct(s) => s.clone(),
        RustType::Enum(e) => e.clone(),
    }
}

fn to_rust_type_string(t: &RustType) -> String {
    match t {
        RustType::Bool => "bool".to_string(),
        RustType::I64 => "i64".to_string(),
        RustType::F64 => "f64".to_string(),
        RustType::String => "String".to_string(),
        RustType::Value => "serde_json::Value".to_string(),
        RustType::Array(inner) => format!("Vec<{}>", to_rust_type_string(inner)),
        RustType::Struct(name) => name.clone(),
        RustType::Enum(name) => name.clone(),
    }
}